### ISSUE TITLE
New Trip Created Every Time Inventory Tab Is Switched To

### ISSUE THREAD

**Issue by OSRS-Physics** [MosheBenZacharia/GP-Per-Hour#57] opened 2024-09-18 18:25 UTC
When on the inventory tab, if I switch to say the xp or prayer tab and then switch back, a new trip is created.

It also does not track gp/hr if not on the inventory tab.

https://github.com/user-attachments/assets/312cc7a9-4055-434e-9f75-08746ffcc5da

**Comment by MosheBenZacharia** [comment] 2024-09-18 18:42
Hey, just to confirm is this a new issue? A new update just went out yesterday, I wonder if this broke something.

**Comment by paul-mcnamee** [comment] 2024-09-18 18:57
> Hey, just to confirm is this a new issue? A new update just went out yesterday, I wonder if this broke something.

I started observing this behavior today as well. There seem to be some issues when switching between spellbook, prayer, inventory, etc. 

I also was having issues seeing the items bought from shops show up in the trips, not sure if that is related or not. I can make a separate issue for that if it helps. It was removing the trip when the shop interface was opened.

I tried restarting the client to see if it would help but still was seeing the same issues after restarting.

**Comment by MosheBenZacharia** [comment] 2024-09-18 19:30
Thanks for the help guys, I put a PR in for the fix, hopefully it gets merged soon. My bad for not testing this update enough!

https://github.com/runelite/plugin-hub/pull/6614

**Comment by MosheBenZacharia** [comment] 2024-09-18 19:52
merged! should be fixed in 1.9 (you may need to restart runelite to see the update)

**Closed by MosheBenZacharia** 2024-09-18 19:52 UTC
Labels: bug, fixed (pending merge)

**Comment by paul-mcnamee** [comment] 2024-09-18 20:17
Seems to be working as intended now, thanks for the quick fix!
